<?php

// todo: srcset needs h attribute too?

// todo: put this into a function in utility?:
/*

            $sizesToBeFilled = ['_265', '_512', '_768', '_1024', '_1280', '_1920', '_2560', '_3200', '_3840', '_4096'];

            foreach($sizes as $key => $value) {
                if( array_search($key, $sizesToBeFilled) !== false ){
                    $src = $value;
                    $src = LTUtility::getFullURL($src);
        
                    $srcset = $src.' '.substr($key, 1).'w, ' . $srcset;
                    $ix = array_search($key, $sizesToBeFilled);

                    if($ix !== false){
                        array_splice( $sizesToBeFilled, $ix, 1 );
                    }
                }
            }
            // fill rest of sizes with full image
            for($i=0; $i<count($sizesToBeFilled); $i++){
                $srcset .= $full_src.' '.substr($sizesToBeFilled[$i], 1).'w, ';
            }
            $srcet = substr($srcset, 0, -2);

*/

class LayElFunctions{

    public function __construct(){

    }

    // note to myself: html5 video in thumbnail.php is not generated by this
    public static function getHTML5VideoMarkup($videoConfig){
        $model = $videoConfig['model'];
        $playsinline = 'playsinline';
    
        $markup = '';
        $pb = $model['ar'] * 100;
        $autoplay_class = $model['autoplay'] == true ? 'autoplay' : '';

        // cannot do "autoplay" because this would make 'preload="none"' not work.
        /*
        The autoplay attribute has precedence over preload. If autoplay is specified, the browser would obviously need to start downloading the video for playback.
        */
        // https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video
        $autoplay_attr = $model['autoplay'] == true ? 'data-autoplay' : '';
        
        $mute = $model['mute'] == true ? 'muted' : '';
        // every autoplay video must be muted, otherwise safari will not autoplay it when scrolled to in "play_pause_autoplay_videos_on_scroll.js"
        if($model['autoplay'] == true){
            $mute = 'muted';
        }
    
        $loop = $model['loop'] == true ? 'loop' : '';
        $controls = $model['controls'] == true ? 'controls' : '';
        $playIcon = "";
        if( $model['playicon'] == true ){
            $src = get_template_directory_uri().'/frontend/assets/img/play.svg';
            if(LayFrontend_Options::$playicon != ""){
                $src = LayFrontend_Options::$playicon;
            }
            $playIcon = '<img class="html5video-customplayicon" src="'.$src.'">';
        }

        $playpauseonclick = array_key_exists('playpauseonclick', $model) ? $model['playpauseonclick'] : false;
        $playpauseonclick_class = 'playpauseonclick';
    
        if( $playpauseonclick ) {
            $playpauseonclick = true;
        }
    
        if( $playpauseonclick == false){
            $playpauseonclick_class = '';
        }
    
        $sizingClass = $model['ar'] > $model['imgar'] ? 'h100' : 'w100';
        $placeholderImage = "";
        if($videoConfig['showPlaceholderImage'] == true){
            // clone
            $newmodel = json_decode( json_encode($model), true);
            // changing keys to fit for "getLazyImg"
            // setting imgar to ar, otherwise the lazy sizes image's ar is just the video's ar
            if( array_key_exists('imgar', $model) ){
                $imgar = $model['imgar'];
                $newmodel['ar'] = $imgar;
            }
            if( array_key_exists('imgattid', $model) ){
                $imgattid = $model['imgattid'];
                $newmodel['attid'] = $imgattid;
            }

            $placeholderImage = '<div class="html5-video-placeholder-image '.$sizingClass.' '.$playpauseonclick_class.'">'.LayElFunctions::getLazyImg($newmodel).'</div>';
        }

    
        $sizes = $model['sizes'];
        $full = '';
        if( array_key_exists('imgattid', $model) ){
            $imgattid = $model['imgattid'];
            $full = wp_get_attachment_image_src( $imgattid, 'full' );
            $full = $full[0];
        }else{
            $full = LTUtility::getFullURL($sizes['full']);
        }

        $poster = 'poster="'.$full.'"';
        if( array_key_exists('_1280', $sizes) ) {
            $_1280 = '';
            if( array_key_exists('imgattid', $model) ){
                $_1280 = wp_get_attachment_image_src( $imgattid, '_1280' );
                $_1280 = $_1280[0];
            }else{
                $_1280 = LTUtility::getFullURL($sizes['_1280']);
            }
            
            $poster = 'poster="'.$_1280.'"';
        }
        
        // don't need poster when I'm not on touch device
        if ( LTUtility::$isTouchDevice == false ) {
        	$poster = '';
        }
        else if( LTUtility::$isTouchDevice && $model['autoplay'] == true ) {
            // if i'm on touchdevice, do not show "html5-video-placeholder-image" when autoplay is on
            // what do I need "html5-video-placeholder-image" for? Why not just use the "poster" attribute only?
            // probably for having a nice fade-in effect when the video loads and srcset
            // answer: for being able to load responsive sized images
            $placeholderImage = "";
        }
        if( LTUtility::$supportsPlaysInlineOnTouchDevice && $model['autoplay'] == true && LTUtility::$supportsPlaysInlineOnTouchDevice ) {
            // no need for poster here
            $poster = '';
        }
    
        $mp4 = $model['mp4'];
        if( array_key_exists('mp4attid', $model) ) {
            $mp4 = wp_get_attachment_url($model['mp4attid']);
        } else {
            $mp4 = LTUtility::getFullURL($mp4);
        }
    
        $useWrap = true;
        if( array_key_exists('useWrap', $videoConfig) ){
            if( $videoConfig['useWrap'] == false ) {
                $useWrap = false;
            }
        }

        $usePaddingPlaceholder = ( array_key_exists('usePaddingPlaceholder', $videoConfig) && $videoConfig['usePaddingPlaceholder'] ) ? true : false;
    
        $markup = '';
        if( $useWrap ){
            $markup .= '<div class="html5video '.$autoplay_class.'">';
        }
            if( $usePaddingPlaceholder ){
                $markup .= '<div class="ph" style="padding-bottom:'.Lay_LayoutFunctions::replaceCommaWithDot($pb).'%;">';
            }
            $w = array_key_exists('w', $model) ? 'data-w="'.$model['w'].'"' : '';
            $h = array_key_exists('h', $model) ? 'data-h="'.$model['h'].'"' : '';
            
            $markup .=
                $playIcon.$placeholderImage
                .'<video preload="none" '.$w.' '.$h.' data-ar="'.$model['ar'].'" '.$poster.' '.$playsinline.' '.$autoplay_attr.' '.$mute.' '.$loop.' '.$controls.' class="'.$autoplay_class.' '.$playpauseonclick_class.'">';
                    $markup .= '<source src="'.$mp4.'" type="video/mp4">';    
                    // if( array_key_exists('noLazyLoad', $videoConfig) && $videoConfig['noLazyLoad'] == true ) {
                    //     $markup .= '<source src="'.$mp4.'" type="video/mp4">';
                    // }else{
                    //     $markup .= '<source src="" data-src="'.$mp4.'" type="video/mp4">';
                    // }
            $markup .=
                '</video>';
            if( $usePaddingPlaceholder ){
                $markup .= '</div>';
            }
            $markup .= $videoConfig['captionMarkup'];
        if( $useWrap ){
            $markup .= '</div>';
        }
    
        return $markup;
    }

    public static function getHTML5VideoMarkupSimple($model){
    /*
        $model['mute'] = true;
        $model['playpauseonclick'] = false;
        $model['autoplay'] = false;
        $model['controls'] = false;
        $model['playicon'] = false;
        $model['ar']
    */        
        $autoplay_class = $model['autoplay'] == true ? 'autoplay' : '';
        $autoplay_attr = $model['autoplay'] == true ? 'data-autoplay' : '';
        $mute = $model['mute'] == true ? 'muted' : '';
        $loop = $model['loop'] == true ? 'loop' : '';
        $playsinline = 'playsinline';
        $mp4 = $model['mp4'];
        $mp4 = LTUtility::getFullURL($mp4);

        return 
        '<video preload="none" '.$playsinline.' '.$autoplay_attr.' '.$mute.' '.$loop.' class="'.$autoplay_class.'">
            <source src="'.$mp4.'" type="video/mp4">   
        </video>';
    }

    public static function getLazyImg($el){
        if( $el['sizes']['full'] == null ){
            // image does not exist
            return;
        }
        $attid = false;
        $alt = get_bloginfo('name');
        $_alt = '';
        $full = '';
        $full_src = '';
        $srcset = '';
        $smallest_src = '';

        $w_attr = '';
        $h_attr = '';

        // attribute id exists
        if( array_key_exists('attid', $el) ) {
            $attid = $el['attid'];
            $_alt = get_post_meta( $attid, '_wp_attachment_image_alt', true );
            $full = wp_get_attachment_image_src( $attid, 'full' );
            $full_src = $full[0];
            $w_attr = 'data-w="'.$full[1].'"';
            $h_attr = 'data-h="'.$full[2].'"';
            $srcset = wp_get_attachment_image_srcset( $attid );
            // todo: test if image smaller than 265 width works
            $smallest = wp_get_attachment_image_src( $attid, '_265' );
            $smallest_src = $full_src;
            if( $smallest != false ) {
                $smallest_src = $smallest[0];
            }
        }
        // there was some freak bug with some website (http://a184.uk/), where wp_get_attachment_image_srcset would always return '' and i could not figure out why, so i do this instead of just else{
        if( $srcset == '' || $srcset == false || !array_key_exists('attid', $el) ){
            // for backwards compatibility
            // todo: test this
            if( array_key_exists('alt', $el) ) {
                $_alt = $el['alt'];
            }
            $full_src = LTUtility::getFullURL($el['sizes']['full']);
            $sizesToBeFilled = ['_265', '_512', '_768', '_1024', '_1280', '_1920', '_2560', '_3200', '_3840', '_4096'];
            $sizes = $el['sizes'];

            foreach($sizes as $key => $value) {
                if( array_search($key, $sizesToBeFilled) !== false ){
                    $src = $value;
                    $src = LTUtility::getFullURL($src);
        
                    $srcset = $src.' '.substr($key, 1).'w, ' . $srcset;
                    $ix = array_search($key, $sizesToBeFilled);

                    if($ix !== false){
                        array_splice( $sizesToBeFilled, $ix, 1 );
                    }
                }
            }
            // fill rest of sizes with full image
            for($i=0; $i<count($sizesToBeFilled); $i++){
                $srcset .= $full_src.' '.substr($sizesToBeFilled[$i], 1).'w, ';
            }
            $srcset = substr( $srcset, 0, -2);
 
            $smallest = array_key_exists('_265', $sizes) ? $sizes['_265'] : false;
            if( $smallest == '' || $smallest == false ) {
                $smallest_src = $full_src;
            } else {
                $smallest_src = LTUtility::getFullURL($smallest);
            }
        }

        if( $_alt != '' ) {
            $alt = $_alt;
        }
        $ar = $el['ar'];

        $isGif = false;
        $isGif = substr($full_src, -4) == '.gif' ? true : false;
        // used by imagehover addon
        $extra = array_key_exists('extra_attrs', $el) ? $el['extra_attrs'] : '';
        $extra_classes = array_key_exists('extra_classes', $el) ? $el['extra_classes'] : '';
        switch( LayFrontend_Options::$image_loading ) {
            case 'instant_load':
                if( $isGif ) {
                    return '<img class="lay-gif '.$extra_classes.'" src="data:image/png;base64,R0lGODlhFAAUAIAAAP///wAAACH5BAEAAAAALAAAAAAUABQAAAIRhI+py+0Po5y02ouz3rz7rxUAOw==" data-src="'.$full_src.'" data-ar="'.$ar.'" alt="'.$alt.'" '.$extra.' '.$w_attr.' '.$h_attr.'/>';
                }
                if( LayFrontend_Options::$misc_options_showoriginalimages && !LTUtility::$isPhone ){
                    return '<img class="lay-image-original '.$extra_classes.'" src="data:image/png;base64,R0lGODlhFAAUAIAAAP///wAAACH5BAEAAAAALAAAAAAUABQAAAIRhI+py+0Po5y02ouz3rz7rxUAOw==" data-src="'.$full_src.'" data-ar="'.$ar.'" alt="'.$alt.'" '.$extra.' '.$w_attr.' '.$h_attr.'/>';
                }
                return '<img class="lay-image-responsive setsizes '.$extra_classes.'" src="data:image/png;base64,R0lGODlhFAAUAIAAAP///wAAACH5BAEAAAAALAAAAAAUABQAAAIRhI+py+0Po5y02ouz3rz7rxUAOw==" data-src="'.$smallest_src.'" data-srcset="'.$srcset.'" sizes="" data-ar="'.$ar.'" alt="'.$alt.'" '.$extra.' '.$w_attr.' '.$h_attr.'/>';
            break;
            case 'lazy_load':
                if( $isGif ) {
                    return '<img class="lay-gif lazyload '.$extra_classes.'" src="data:image/png;base64,R0lGODlhFAAUAIAAAP///wAAACH5BAEAAAAALAAAAAAUABQAAAIRhI+py+0Po5y02ouz3rz7rxUAOw==" data-src="'.$full_src.'" data-ar="'.$ar.'" alt="'.$alt.'" '.$extra.' '.$w_attr.' '.$h_attr.'/>';
                }
                if( LayFrontend_Options::$misc_options_showoriginalimages && !LTUtility::$isPhone ){
                    return '<img class="lay-image-original lazyload '.$extra_classes.'" src="data:image/png;base64,R0lGODlhFAAUAIAAAP///wAAACH5BAEAAAAALAAAAAAUABQAAAIRhI+py+0Po5y02ouz3rz7rxUAOw==" data-src="'.$full_src.'" data-ar="'.$ar.'" alt="'.$alt.'" '.$extra.' '.$w_attr.' '.$h_attr.'/>';
                }
                return '<img class="lay-image-responsive lazyload '.$extra_classes.'" src="data:image/png;base64,R0lGODlhFAAUAIAAAP///wAAACH5BAEAAAAALAAAAAAUABQAAAIRhI+py+0Po5y02ouz3rz7rxUAOw==" data-src="'.$smallest_src.'" data-srcset="'.$srcset.'" data-ar="'.$ar.'" data-sizes="auto" alt="'.$alt.'" '.$extra.' '.$w_attr.' '.$h_attr.'/>';
            break;
        }

    }

    public static function getMouseOverThumbImg($el) {
        $ar = (int)$el['mo_h'] / (int)$el['mo_w'];
        $isGif = false;
        $mo_attid = array_key_exists('mo_attid', $el) ? $el['mo_attid'] : false;
        $alt = get_bloginfo('name');
        $full = '';
        $full_src = '';
        $srcset = '';
        $smallest_src = '';

        if( $mo_attid != false ) {
            $alt = get_post_meta( $mo_attid, '_wp_attachment_image_alt', true );
            $full = wp_get_attachment_image_src( $mo_attid, 'full' );
            $full_src = $full[0];
            $smallest = wp_get_attachment_image_src( $mo_attid, '_265' );
            $smallest_src = $smallest[0];
            $srcset = wp_get_attachment_image_srcset( $mo_attid );
        } else {
            // for backwards compatibility
            $sizes = $el['mo_sizes'];
            $full_src = LTUtility::getFullURL($el['mo_sizes']['full']);
            $sizesToBeFilled = ['_265', '_512', '_768', '_1024', '_1280', '_1920', '_2560', '_3200', '_3840', '_4096'];
            $smallest_src = $sizes['_265'];

            foreach($sizes as $key => $value) {
                if( array_search($key, $sizesToBeFilled) !== false ){
                    $src = $value;
                    $src = LTUtility::getFullURL($src);
        
                    $srcset = $src.' '.substr($key, 1).'w, ' . $srcset;
                    $ix = array_search($key, $sizesToBeFilled);

                    if($ix !== false){
                        array_splice( $sizesToBeFilled, $ix, 1 );
                    }
                }
            }
            // fill rest of sizes with full image
            for($i=0; $i<count($sizesToBeFilled); $i++){
                $srcset .= $full_src.' '.substr($sizesToBeFilled[$i], 1).'w, ';
            }
            $srcset = substr($srcset, 0, -2);
        }
        $isGif = substr($full_src, -4) == '.gif' ? true : false;

        // same as in getLazyImg, but using class "mo_thumb"
        switch( LayFrontend_Options::$image_loading ) {
            case 'instant_load':
                if( $isGif ) {
                    return '<img class="mo_thumb lay-gif" src="data:image/png;base64,R0lGODlhFAAUAIAAAP///wAAACH5BAEAAAAALAAAAAAUABQAAAIRhI+py+0Po5y02ouz3rz7rxUAOw==" data-src="'.$full_src.'" data-ar="'.$ar.'" alt="'.$alt.'"/>';
                }
                if( LayFrontend_Options::$misc_options_showoriginalimages && !LTUtility::$isPhone ){
                    return '<img class="mo_thumb lay-image-original" src="data:image/png;base64,R0lGODlhFAAUAIAAAP///wAAACH5BAEAAAAALAAAAAAUABQAAAIRhI+py+0Po5y02ouz3rz7rxUAOw==" data-src="'.$full_src.'" data-ar="'.$ar.'" alt="'.$alt.'"/>';
                }
                return '<img class="mo_thumb lay-image-responsive setsizes" src="data:image/png;base64,R0lGODlhFAAUAIAAAP///wAAACH5BAEAAAAALAAAAAAUABQAAAIRhI+py+0Po5y02ouz3rz7rxUAOw==" data-src="'.$smallest_src.'" data-srcset="'.$srcset.'" sizes="" data-ar="'.$ar.'" alt="'.$alt.'"/>';
            break;
            case 'lazy_load':
                if( $isGif ) {
                    return '<img class="mo_thumb lay-gif lazyload" src="data:image/png;base64,R0lGODlhFAAUAIAAAP///wAAACH5BAEAAAAALAAAAAAUABQAAAIRhI+py+0Po5y02ouz3rz7rxUAOw==" data-src="'.$full_src.'" data-ar="'.$ar.'" alt="'.$alt.'"/>';
                }
                if( LayFrontend_Options::$misc_options_showoriginalimages && !LTUtility::$isPhone ){
                    return '<img class="mo_thumb lay-image-original lazyload" src="data:image/png;base64,R0lGODlhFAAUAIAAAP///wAAACH5BAEAAAAALAAAAAAUABQAAAIRhI+py+0Po5y02ouz3rz7rxUAOw==" data-src="'.$full_src.'" data-ar="'.$ar.'" alt="'.$alt.'"/>';
                }
                return '<img class="mo_thumb lay-image-responsive lazyload" src="data:image/png;base64,R0lGODlhFAAUAIAAAP///wAAACH5BAEAAAAALAAAAAAUABQAAAIRhI+py+0Po5y02ouz3rz7rxUAOw==" data-src="'.$smallest_src.'" data-srcset="'.$srcset.'" data-ar="'.$ar.'" data-sizes="auto" alt="'.$alt.'"/>';
            break;
        }
    }

    public static function stringifyCatIds($catids){
        if( $catids == '' || $catids == null  ) {
            return '[]';
        }
        if( is_string($catids) ) {
            return $catids;
        }
        // is a number like 3
        if( is_scalar($catids) ) {
            return '['.$catids.']';
        }
        if( is_array($catids) ) {
            for( $i=0; $i<count($catids); $i++ ) {
                $catids[$i] = (int)$catids[$i];
            }
        }
        return json_encode($catids);
    }

    public static function getCaptionMarkup($el){
        if( array_key_exists( 'caption', $el ) ) {
            return '<div class="caption lay-textformat-parent">'.$el['caption'].'</div>'; 
        }
        return '';
    }

    // this function accepts an array of postids
    public static function get_thumbnails_data_for_thumbnailgrid_by_ids( $ids ){
		$array = array();

		// generating an array of objects that contain all the info needed to create a thumbnailgrid
		foreach ($ids as $post_id){
			if(get_post_status($post_id) != "publish"){
				continue;
			}
			$attid = get_post_thumbnail_id($post_id);

			$sizes = array();
			for ($i=0; $i < count(Setup::$sizes); $i++) {
				$attachment = wp_get_attachment_image_src($attid, Setup::$sizes[$i]);
				$sizes[Setup::$sizes[$i]] = $attachment[0];
			}
			$full = wp_get_attachment_image_src($attid, 'full');
			$sizes['full'] = $full[0];

			$ar = 0;
			if($full){
				if($full[1] != 0){
					$ar = $full[2] / $full[1];
				}
			}

			// mouseover thumbnail image
			$mouseOverThumbSizesArr = array();
			$mouseOverThumbWidth = "";
			$mouseOverThumbHeight = "";
			if(ImageMouseoverThumbnails::$active == true){
				$mouseover_thumbnail_id = get_post_meta( $post_id, '_lay_thumbnail_mouseover_image', true );

				if ( $mouseover_thumbnail_id && get_post( $mouseover_thumbnail_id ) ) {
					for ($i=0; $i < count(Setup::$sizes); $i++) {
						$attachment = wp_get_attachment_image_src($mouseover_thumbnail_id, Setup::$sizes[$i]);
						$mouseOverThumbSizesArr[Setup::$sizes[$i]] = $attachment[0];
					}
					$full = wp_get_attachment_image_src($mouseover_thumbnail_id, 'full');
					$mouseOverThumbSizesArr['full'] = $full[0];
					$mouseOverThumbWidth = $full[1];
					$mouseOverThumbHeight = $full[2];
				}
			}
			// video thumbnail
			$video_url = "";
			$video_meta = array('width'=>'', 'height'=>'');
			if(VideoThumbnails::$active == true){
				$video_id = get_post_meta( $post_id, '_lay_thumbnail_video', true );
				if($video_id != ""){
					$video_url = wp_get_attachment_url($video_id);
					$video_meta = wp_get_attachment_metadata($video_id);
				}
            }
            $video_w = '';
            $video_h = '';
            // error_log(print_r($video_meta, true));
            if( is_array($video_meta) && isset($video_meta["width"]) && isset($video_meta["height"]) ) {
                $lastIx = count($array) - 1;
                $video_w = $video_meta["width"];
                $video_h = $video_meta["height"];
            }

			$array []= array(
				"type" => "img",
				"title" => get_the_title($post_id),
				"attid" => $attid,
				"postid" => $post_id,
				"ar" => $ar,
				'sizes' => $sizes,
				"link" => get_permalink($post_id),
				"descr" => get_post_meta( $post_id, 'lay_project_description', true ),
				"mo_sizes" => $mouseOverThumbSizesArr,
	   			"mo_w" => $mouseOverThumbWidth,
	   			"mo_h" => $mouseOverThumbHeight,
                "video_url" => $video_url,
                "video_w" => $video_w,
                "video_h" => $video_h
            );
		}

		return $array;
    }

    // this function just returns the neccessary data to create a thumbnailgrid
    public static function get_thumbnails_data_for_thumbnailgrid_by_catid( $cat_id ){
		$ids = Thumbnailgrid::get_project_ids_possibly_with_order($cat_id);
        return LayElFunctions::get_thumbnails_data_for_thumbnailgrid_by_ids($ids);
	}

}
new LayElFunctions();